# Generated by Django 5.0 on 2023-12-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_are', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_are', models.CharField(max_length=50, unique=True)),
                ('estado_are', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
