# Generated by Django 5.0 on 2023-12-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admRrhh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_carg', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_carg', models.CharField(max_length=50)),
                ('estado_carg', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
