# Generated by Django 5.0 on 2024-01-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admRrhh', '0003_asignacion_documento_estudio_fiscal_parentesco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio',
            name='asignacion_env',
        ),
        migrations.AddField(
            model_name='envio',
            name='proyecto_env',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admRrhh.proyecto'),
        ),
    ]
