# Generated by Django 5.0 on 2024-07-13 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admRrhh', '0004_remove_envio_asignacion_env_envio_proyecto_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='fechVenlic_perl',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha vencimiento de licencia'),
        ),
    ]
